# Site settings
title: Web log of agrawal-d
description: "agrawal-d, a programmer, shares his adventures with you."
url: "http://www.dyutibarma.github.io/monochrome"
author:
  name: "Divyanshu Agrawal"
  email: "agrawal.divyanshu+blog@outlook.com"
  url: "https://agrawal-d.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins: [jekyll-paginate, jekyll-sitemap]

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
